### ISSUE TITLE
Vehicle properties

### ISSUE THREAD

**Issue by joserodriguezballester** [Sgambe33/WTVehiclesAPI#1]
The "sensor" property appears in the vehicle list, but not when a call is made to the vehicle.
There is no "imageUrl" property which should be = url+ identifier + ".png"

**Comment by Sgambe33** [comment]
Are you sure about the first one? I just checked and it is present in the response

**Comment by joserodriguezballester** [comment]
![Captura de pantalla 2024-01-26 214241](https://github.com/Sgambe33/WTVehiclesAPI/assets/50195702/23d066fe-c75b-40d5-abac-f9341863a305)
![Captura de pantalla 2024-01-26 214405](https://github.com/Sgambe33/WTVehiclesAPI/assets/50195702/d0a2a3e3-497b-49b6-a1ac-2bd0604c6796)

**Comment by Sgambe33** [comment]
Ah, I see what you mean. Perhaps I forgot to update the API server-side, will investigate and also add the images urls.

**Comment by joserodriguezballester** [comment]
![Captura de pantalla 2024-01-26 232645](https://github.com/Sgambe33/WTVehiclesAPI/assets/50195702/c9b54302-c6f9-436e-a1c9-4f7173756e6a)
Thank you; look at my first version

**Comment by Sgambe33** [comment]
The commits 99eb18c and aef838c should fix the problems. Anyway I advise to not use the sensors field yet as it's very raw and not easily understandable. Please close the issue if everything works.
